apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades-historical
  namespace: rwml
  labels:
    app: trades-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades-historical
  template:
    metadata:
      labels:
        app: trades-historical  
    spec:
      containers:
      - name: trades-historical
        image: trades:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC_NAME
          value: "trades_historical"
        - name: LIVE_OR_HISTORICAL
          value: "historical"
        - name: LAST_N_DAYS
          value: "30" # Adjust this value as needed for the historical backfill
        # - name: PRODUCT_ID
        #   value: |
        #     - BTC-USD
        #     - BTC-EUR
        #     - ETH-USD
        #     - ETH-EUR
        #     - SOL-USD
        #     - SOL-EUR
        #     - XRP-USD
        #     - XRP-EUR 
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: candles-historical
  namespace: rwml
  labels:
    app: candles-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: candles-historical
  template:
    metadata:
      labels:
        app: candles-historical
    spec:
      containers:
      - name: candles-historical
        image: candles:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "candles"
        - name: KAFKA_INPUT_TOPIC
          value: "trades_historical"
        - name: KAFKA_OUTPUT_TOPIC
          value: "candles_historical"
        - name: CANDLES_SECONDS
          value: "60"
        - name: KAFKA_CONSUMER_GROUP
          value: "candles_consumer_group"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: technical-indicators-historical
  namespace: rwml
  labels:
    app: technical-indicators-historical
spec:
  replicas: 1
  selector:
    matchLabels:
      app: technical-indicators-historical
  template:
    metadata:
      labels:
        app: technical-indicators-historical
    spec:
      containers:
      - name: technical-indicators-historical
        image: technical_indicators:dev
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_INPUT_TOPIC
          value: "candles_historical"
        - name: KAFKA_OUTPUT_TOPIC
          value: "technical_indicators"
        - name: KAFKA_CONSUMER_GROUP
          value: "technical_indicators_group_2"
        - name: CANDLE_SECONDS
          value: "60"