apiVersion: apps/v1
kind: Deployment
metadata:
  name: trades
  namespace: rwml-prod
  labels:
    app: trades
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trades
  template:
    metadata:
      labels:
        app: trades
    spec:
      containers:
      - name: trades
        image: docker pull ghcr.io/mahmoudmoe84/trades:0.1.3-beta.1745656056
        imagePullPolicy: Never # Use the local image
        env:
        - name: KAFKA_BROKER_ADDRESS
          value: kafka-e11b-kafka-bootstrap.kafka.svc.cluster.local:9092
        - name: KAFKA_TOPIC
          value: "trades"